/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alattulis.view;

import alattulis.controller.controllerKaryawan;
import alattulis.controller.controllerLogin;
import alattulis.model.modelKaryawan;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author My PC
 */
public class FormTampilKaryawan extends javax.swing.JFrame {

private final controllerKaryawan controllerKaryawan = new controllerKaryawan();    
private final controllerLogin controllerLogin = new controllerLogin();

    public FormTampilKaryawan() {
        initComponents();
        setTableKaryawan(controllerKaryawan.getAllData());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        puTable = new javax.swing.JPopupMenu();
        mnDeletePP = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKaryawan = new javax.swing.JTable();
        btnTambahKaryawan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        mnDeletePP.setText("hapus");
        mnDeletePP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDeletePPActionPerformed(evt);
            }
        });
        puTable.add(mnDeletePP);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblKaryawanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblKaryawanMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblKaryawan);

        btnTambahKaryawan.setText("Tambah Karyawan");
        btnTambahKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahKaryawanActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambahKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahKaryawan)
                    .addComponent(btnKembali))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahKaryawanActionPerformed
        new FormTambahKaryawan(this, rootPaneCheckingEnabled).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTambahKaryawanActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new FormMain().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void mnDeletePPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDeletePPActionPerformed
        int result = JOptionPane.showConfirmDialog(rootPane,
            "Apakah data ini akan dihapus ?",
            "Dialog Hapus", JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
            String nik = tblKaryawan.getModel().getValueAt(tblKaryawan.getSelectedRow(), 0).toString();
            controllerLogin.deleteLogin(nik);
            controllerKaryawan.deleteKaryawan(nik);
            
        }
    }//GEN-LAST:event_mnDeletePPActionPerformed

    private void tblKaryawanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKaryawanMousePressed
        if(evt.getClickCount() == 2){
            int idxrow = tblKaryawan.getSelectedRow();
            
        }
        if(evt.isPopupTrigger()){
            puTable.show(tblKaryawan, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tblKaryawanMousePressed

    private void tblKaryawanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKaryawanMouseReleased
        if(evt.getClickCount() == 2){
            int idxrow = tblKaryawan.getSelectedRow();
            
        }
        if(evt.isPopupTrigger()){
            puTable.show(tblKaryawan, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tblKaryawanMouseReleased

    private void setTableKaryawan(List<modelKaryawan> listmodelKaryawan) {
       if (listmodelKaryawan==null){
           JOptionPane.showMessageDialog(this, "Data karyawan gagal diambil dari database",
                   "DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
       }else{
           DefaultTableModel tableModel = new DefaultTableModel();
           tableModel.setColumnIdentifiers(
               new String[] {
                   "NIK",
                   "Nama Karyawan",
                   "Lahir Karyawan",
                   "Kelamin Karyawan",
                   "Alamat Karyawan",
                   "Email Karyawan"
               }
           );

           for (modelKaryawan g : listmodelKaryawan) {
               Object[] o = new Object[6];
               o[0] = g.getNik();
               o[1] = g.getNama_karyawan();
               o[2] = g.getLahir_karyawan();
               o[3] = g.getKelamin_karyawan();
               o[4] = g.getAlamat_karyawan();
               o[5] = g.getEmail_karyawan();
               tableModel.addRow(o);
           }
           tblKaryawan.setAutoResizeMode( javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS );
           tblKaryawan.setModel(tableModel);
       }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTampilKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTampilKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTampilKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTampilKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTampilKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambahKaryawan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnDeletePP;
    private javax.swing.JPopupMenu puTable;
    private javax.swing.JTable tblKaryawan;
    // End of variables declaration//GEN-END:variables
}
