/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alattulis.view;

import alattulis.controller.controllerBarang;
import alattulis.controller.controllerKaryawan;
import alattulis.controller.controllerTransaksi;
import alattulis.model.modelBarang;
import alattulis.model.modelKaryawan;
import alattulis.model.modelTransaksi;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author My PC
 */
public class FormTransaksi extends javax.swing.JFrame {

    controllerKaryawan controllerKaryawan = new controllerKaryawan();
    controllerBarang controllerBarang = new controllerBarang();
    controllerTransaksi controllerTransaksi = new controllerTransaksi();
    List<modelTransaksi> collection = new ArrayList<>();
    int totalpembelian = 0;
    
    public FormTransaksi() {
        initComponents();
        initData();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchData = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        txtPencarian = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        lblIdTransaksi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        btnTamBar = new javax.swing.JButton();
        btnKurBar = new javax.swing.JButton();
        btnNamaKar = new javax.swing.JButton();
        lblIdKaryawan = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtJumBay = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        lblTotBel = new javax.swing.JLabel();
        lblKembalian = new javax.swing.JLabel();

        searchData.setAlwaysOnTop(true);
        searchData.setMinimumSize(new java.awt.Dimension(600, 600));

        jLabel8.setText("Nama");

        txtPencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPencarianKeyTyped(evt);
            }
        });

        btnCari.setText("Cari");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasil Pencarian"));

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblResultMousePressed(evt);
            }
        });
        jScrollPane5.setViewportView(tblResult);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout searchDataLayout = new javax.swing.GroupLayout(searchData.getContentPane());
        searchData.getContentPane().setLayout(searchDataLayout);
        searchDataLayout.setHorizontalGroup(
            searchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(txtPencarian, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCari)
                .addContainerGap())
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        searchDataLayout.setVerticalGroup(
            searchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transaksi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("Tanggal");

        jLabel2.setText("Id Transaksi");

        jLabel3.setText("Karyawan");

        lblTanggal.setText("tanggal_transaksi");

        lblIdTransaksi.setText("lblIdTransaksi");

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTransaksi);

        btnTamBar.setText("+");
        btnTamBar.setMaximumSize(new java.awt.Dimension(41, 27));
        btnTamBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTamBarActionPerformed(evt);
            }
        });

        btnKurBar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnKurBar.setText("-");
        btnKurBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKurBarActionPerformed(evt);
            }
        });

        btnNamaKar.setText("Search Nama Karyawan");
        btnNamaKar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNamaKarActionPerformed(evt);
            }
        });

        lblIdKaryawan.setText("id_karyawan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdTransaksi)
                    .addComponent(lblTanggal)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblIdKaryawan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNamaKar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTamBar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKurBar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTanggal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblIdTransaksi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnNamaKar)
                    .addComponent(lblIdKaryawan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKurBar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnTamBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kalkulasi Pembayaran", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel4.setText("Total Pembelian");

        jLabel5.setText("Jumlah Bayar");

        jLabel6.setText("Kembalian");

        txtJumBay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJumBayKeyTyped(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTutup.setText("Tutup");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotBel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSimpan)
                            .addComponent(btnTutup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addComponent(txtJumBay, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTotBel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnSimpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnTutup)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(txtJumBay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTamBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamBarActionPerformed
        setTableBarang(controllerBarang.getAllData());
        searchData.setVisible(true);
    }//GEN-LAST:event_btnTamBarActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    private void txtPencarianKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPencarianKeyTyped
        String colName = tblResult.getColumnModel().getColumn(0).getHeaderValue().toString();
        if(colName.equals("NIK")){
            setTableKaryawan(controllerKaryawan.getAllKaryawanByName(txtPencarian.getText()));
        } else{
            setTableBarang(controllerBarang.getAllBarangByName(txtPencarian.getText()));
        }
    }//GEN-LAST:event_txtPencarianKeyTyped

    private void tblResultMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultMousePressed
        this.setLocationRelativeTo(null);
        if(evt.getClickCount() == 2){
            String colName = tblResult.getColumnModel().getColumn(0).getHeaderValue().toString();
            int idxrow = tblResult.getSelectedRow();
            if(colName.equals("NIK")){
                btnNamaKar.setText(tblResult.getModel().getValueAt(idxrow, 1).toString());
                lblIdKaryawan.setText(tblResult.getModel().getValueAt(idxrow, 0).toString());
            }else{
                
                String id_transaksi = lblIdTransaksi.getText();
                int id_karyawan = 0;
                int id_barang = Integer.parseInt(tblResult.getModel().getValueAt(idxrow, 0).toString());
                String kode_barang = tblResult.getModel().getValueAt(idxrow, 2).toString();
                String tanggal_transaksi = "";
                int sub_total = Integer.parseInt(tblResult.getModel().getValueAt(idxrow,3).toString());
                int jumlah_bayar = 0;

                modelTransaksi data = new modelTransaksi (id_transaksi, id_karyawan, 
                                                         id_barang, kode_barang, tanggal_transaksi,
                                                         sub_total, jumlah_bayar);
                
                totalpembelian += sub_total;
                lblTotBel.setText(totalpembelian+"") ;
                
                collection.add(data);
            }
            searchData.dispose();
            setTableTransaksi(collection);
        }
    }//GEN-LAST:event_tblResultMousePressed

    private void btnKurBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurBarActionPerformed
        if(collection.size() >= 0){
            totalpembelian -= collection.get(0).getSub_total(); 
            lblTotBel.setText(totalpembelian+"");
            collection.remove(0);
            setTableTransaksi(collection);
        }
    }//GEN-LAST:event_btnKurBarActionPerformed

    private void btnNamaKarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNamaKarActionPerformed
        setTableKaryawan(controllerKaryawan.getAllData());
        searchData.setVisible(true);
    }//GEN-LAST:event_btnNamaKarActionPerformed

    private void txtJumBayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumBayKeyTyped
        if(evt.getKeyCode() == 0){
           if(!txtJumBay.getText().equals("")){
                int uang = Integer.parseInt(txtJumBay.getText());
                int totbay = Integer.parseInt(lblTotBel.getText());
                float change = uang - totbay;
                lblKembalian.setText(change < 0 ? 0+"" : change+"");
            }
        }
    }//GEN-LAST:event_txtJumBayKeyTyped

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
       
        int idxrow = tblResult.getSelectedRow();
        
        String id_transaksi = lblIdTransaksi.getText();
        int id_karyawan = Integer.parseInt(lblIdKaryawan.getText().toString());
        int id_barang = Integer.parseInt(tblTransaksi.getModel().getValueAt(idxrow, 1).toString());
        String kode_barang = (tblTransaksi.getModel().getValueAt(idxrow, 2).toString());
        String tanggal_transaksi = lblTanggal.getText();
        int sub_total = Integer.parseInt(lblTotBel.getText());
        int jumlah_bayar = Integer.parseInt(txtJumBay.getText().toString());
        
        modelTransaksi tran = new modelTransaksi(
                id_transaksi,
                id_karyawan,
                id_barang,
                kode_barang,
                tanggal_transaksi,
                sub_total,
                jumlah_bayar                       
            );
            controllerTransaksi.insertmodelTransaksi(tran);
            
            setClear();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void setTableBarang(List<modelBarang> listBarang) {
       if (listBarang==null){
           JOptionPane.showMessageDialog(this, "Data barang gagal diambil dari database","DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
       }else{
           DefaultTableModel tableModel = new DefaultTableModel();
           tableModel.setColumnIdentifiers(
               new String[] {
                   "Id Barang",
                   "Nama Barang",
                   "Kode Barang",
                   "Harga Barang",
                   "Stok Barang"
               }
           );

           for (modelBarang s : listBarang) {
               Object[] o = new Object[5];
               o[0] = s.getId_barang();
               o[1] = s.getNama_barang();
               o[2] = s.getKode_barang();
               o[3] = s.getHarga_barang();
               o[4] = s.getStok_barang();
               tableModel.addRow(o);
           }
           tblResult.setAutoResizeMode( javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS );
           tblResult.setModel(tableModel);
       }
    }
    
    private void setTableKaryawan(List<modelKaryawan> listmodelKaryawan) {
       if (listmodelKaryawan==null){
           JOptionPane.showMessageDialog(this, "Data karyawan gagal diambil dari database",
                   "DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
       }else{
           DefaultTableModel tableModel = new DefaultTableModel();
           tableModel.setColumnIdentifiers(
               new String[] {
                   "NIK",
                   "Nama Karyawan",
                   "Lahir Karyawan",
                   "Kelamin Karyawan",
                   "Alamat Karyawan",
                   "Email Karyawan"
               }
           );

           for (modelKaryawan g : listmodelKaryawan) {
               Object[] o = new Object[6];
               o[0] = g.getNik();
               o[1] = g.getNama_karyawan();
               o[2] = g.getLahir_karyawan();
               o[3] = g.getKelamin_karyawan();
               o[4] = g.getAlamat_karyawan();
               o[5] = g.getEmail_karyawan();
               tableModel.addRow(o);
           }
           tblResult.setAutoResizeMode( javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS );
           tblResult.setModel(tableModel);
       }
    }
    
    private void setTableTransaksi(List<modelTransaksi> listTransaksi){
        if (listTransaksi==null){
           JOptionPane.showMessageDialog(this, "Data produk gagal diambil dari database","DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
       }else{
           DefaultTableModel tableModel = new DefaultTableModel();
           tableModel.setColumnIdentifiers(
               new String[] {
                   "Id Transaksi",
                   "Id Barang",
                   "Kode Barang",                  
                   "Harga"
                   
               }
           );
           
           for (modelTransaksi g : listTransaksi) {
               Object[] o = new Object[4];
               
               o[0] = controllerTransaksi.generateIDtransaksi();
               o[1] = g.getId_barang();
               o[2] = g.getKode_barang();
               o[3] = g.getSub_total();
               
               
               tableModel.addRow(o);
           }
           tblTransaksi.setAutoResizeMode( javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS );
           tblTransaksi.setModel(tableModel);
       }
    } 
    

    
    public void initData(){
        Calendar c = Calendar.getInstance();
        String date = c.get(Calendar.YEAR) +"/"+ (c.get(Calendar.MONTH)+1) +"/"+ c.get(Calendar.DATE);
        lblTanggal.setText(date);
        lblIdTransaksi.setText(controllerTransaksi.generateIDtransaksi()+"");
        setTableTransaksi(collection);
    }
    
    private void setClear(){
        //membersihkan data transaksi

        btnNamaKar.setText("nama_karyawan");
        lblIdKaryawan.setText("id_karyawan");
        
        
        //membersihkan data Table transaksi
        collection.clear();
        setTableTransaksi(collection);
        
       
        //membersihkan data kalkulasi
        lblTotBel.setText("0");
        txtJumBay.setText("0");
        lblKembalian.setText("0");
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnKurBar;
    private javax.swing.JButton btnNamaKar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTamBar;
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblIdKaryawan;
    private javax.swing.JLabel lblIdTransaksi;
    private javax.swing.JLabel lblKembalian;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblTotBel;
    private javax.swing.JDialog searchData;
    private javax.swing.JTable tblResult;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextField txtJumBay;
    private javax.swing.JTextField txtPencarian;
    // End of variables declaration//GEN-END:variables
}
